trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet restore
      dotnet build --configuration $(buildConfiguration)
    displayName: 'Restore and Build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      arguments: '--configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/Output'
      publishWebProjects: true

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure Vue Workshop'
      appName: 'simple-api-dotnet'
      package: '$(Build.ArtifactStagingDirectory)/Output/**/*.zip'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure Vue Workshop'
      appType: 'webAppLinux'
      appName: 'simple-api-dotnet'
      package: '$(Build.ArtifactStagingDirectory)/app.zip'
