trigger:
  branches:
    include:
      - main  # Change this to your default branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'  # Specify .NET Core 8 SDK version
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet restore
      dotnet build --configuration Release
    displayName: 'Restore and Build'

  - script: |
      dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
    displayName: 'Publish'

  - script: |
      echo "Listing published files:"
      ls -la $(Build.ArtifactStagingDirectory)  # List files for verification
    displayName: 'List Published Files'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure Vue Workshop'  # Replace with your Azure subscription name
      appType: 'webApp'  # Or 'functionApp'
      appName: 'simple-api-dotnet'  # Replace with your Azure Web App name
      package: '$(Build.ArtifactStagingDirectory)/**/*'  # Path to the published output
