trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      version: '8.x'
      performMultiLevelLookup: true
      includePreviewVersions: true # Required for preview

  - script: |
      dotnet restore
      dotnet build --configuration $(buildConfiguration)
    displayName: 'Restore and Build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(BuildConfiguration)'
      zipAfterPublish: True

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'drop'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure Vue Workshop'
      appName: 'simple-api-dotnet'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
