trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet restore
      dotnet build --configuration Release
    displayName: 'Restore and Build'

  - script: |
      dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
    displayName: 'Publish'

  - script: |
      echo "Listing published files:"
      ls -la $(Build.ArtifactStagingDirectory)  # List files for verification
    displayName: 'List Published Files'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure Vue Workshop'
      appType: 'webAppLinux'
      appName: 'simple-api-dotnet'
      package: '$(Build.ArtifactStagingDirectory)/**/*'
